/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package netbeans_gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import model.Concession;
import model.Customer;

/**
 *
 * @author Kahden Vienna
 */
public class ConcessionMenuC extends javax.swing.JFrame {

    private JComboBox<String> itemDropdown;
    private JSpinner quantitySpinner;
    private JTextArea orderSummary;
    private JLabel totalLabel;
    private Map<String, Integer> cart = new HashMap<>();
    private Customer currentUser;

    /**
     * Creates new form ConcessionMenuC
     */
    public ConcessionMenuC(Customer currentUser) {
        this.currentUser = currentUser;
        setTitle("Concession Stand - Customer View");
        setSize(700, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(null);

        // Title Label
        JLabel titleLabel = new JLabel("Concession Stand");
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 36));
        titleLabel.setBounds(200, 20, 300, 50);
        add(titleLabel);

        // Item Dropdown
        JLabel itemLabel = new JLabel("Select Item:");
        itemLabel.setBounds(100, 100, 120, 25);
        add(itemLabel);

        itemDropdown = new JComboBox<>();
        loadConcessionItems();
        itemDropdown.setBounds(250, 100, 150, 25);
        add(itemDropdown);

        // Quantity Spinner
        JLabel quantityLabel = new JLabel("Quantity:");
        quantityLabel.setBounds(100, 140, 120, 25);
        add(quantityLabel);

        quantitySpinner = new JSpinner(new SpinnerNumberModel(1, 1, 10, 1));
        quantitySpinner.setBounds(250, 140, 50, 25);
        add(quantitySpinner);

        // Order Summary
        JLabel orderLabel = new JLabel("Order Summary:");
        orderLabel.setBounds(100, 180, 120, 25);
        add(orderLabel);

        orderSummary = new JTextArea();
        orderSummary.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(orderSummary);
        scrollPane.setBounds(250, 180, 250, 100);
        add(scrollPane);

        // Total Label
        totalLabel = new JLabel("Total: $0.00");
        totalLabel.setBounds(200, 300, 120, 25);
        add(totalLabel);

        // Add to Cart Button
        JButton addToCartButton = new JButton("Add to Cart");
        addToCartButton.setBounds(150, 350, 120, 30);
        add(addToCartButton);
        addToCartButton.addActionListener(this::handleAddToCart);

        // Checkout Button
        JButton checkoutButton = new JButton("Checkout");
        checkoutButton.setBounds(300, 350, 120, 30);
        add(checkoutButton);
        checkoutButton.addActionListener(this::handleCheckout);

        // Cancel Button
        JButton cancelButton = new JButton("Cancel");
        cancelButton.setBounds(450, 350, 120, 30);
        add(cancelButton);
        cancelButton.addActionListener(e -> resetSelections());

        setVisible(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void loadConcessionItems() {
        Map<String, Concession> menu = Concession.getConcessionMenu();
        for (String itemId : menu.keySet()) {
            itemDropdown.addItem(menu.get(itemId).getItemName());
        }
    }

    private void handleAddToCart(ActionEvent e) {
        String selectedItemName = (String) itemDropdown.getSelectedItem();
        int quantity = (int) quantitySpinner.getValue();

        cart.put(selectedItemName, cart.getOrDefault(selectedItemName, 0) + quantity);
        updateOrderSummary();
    }

    private void updateOrderSummary() {
        StringBuilder summary = new StringBuilder();
        double total = 0.0;

        for (String itemName : cart.keySet()) {
            Concession item = findConcessionItem(itemName);
            if (item != null) {
                int quantity = cart.get(itemName);
                double cost = item.getPrice() * quantity;
                total += cost;
                summary.append(itemName).append(" x").append(quantity)
                        .append(" - $").append(String.format("%.2f", cost)).append("\n");
            }
        }

        orderSummary.setText(summary.toString());
        totalLabel.setText(String.format("Total: $%.2f", total));
    }

    private Concession findConcessionItem(String itemName) {
        for (Concession item : Concession.getConcessionMenu().values()) {
            if (item.getItemName().equals(itemName)) {
                return item;
            }
        }
        return null;
    }

    private void handleCheckout(ActionEvent e) {
        if (cart.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Your cart is empty.");
            return;
        }

        String transactionId = "PAY" + System.currentTimeMillis();

        try (BufferedWriter writer = new BufferedWriter(new FileWriter("data/purchases.txt", true))) {
            for (String itemName : cart.keySet()) {
                Concession item = findConcessionItem(itemName);
                int quantity = cart.get(itemName);

                for (int i = 0; i < quantity; i++) {
                    writer.write(currentUser.getId() + "," + itemName + "," +
                                 String.format("%.2f", item.getPrice()) + "," + transactionId);
                    writer.newLine();
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving purchase.");
            return;
        }

        JOptionPane.showMessageDialog(this, "Order placed!\nTransaction ID: " + transactionId);
        resetSelections();
    }

    private void resetSelections() {
        cart.clear();
        orderSummary.setText("");
        totalLabel.setText("Total: $0.00");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
