package netbeans_gui;

import javax.swing.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.io.*;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;

import model.Customer;
import model.Movie;
import io.MovieIO;
import io.ShowtimeIO;

public class CustomerMenu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CustomerMenu_GUI
     */
    private Customer currentUser;

    public CustomerMenu_GUI(Customer currentUser) {
        this.currentUser = currentUser;
        initComponents();
        contentPanel.setLayout(new BoxLayout(contentPanel, BoxLayout.Y_AXIS));
        contentPanel.setPreferredSize(null); // Let it grow dynamically

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Logout_button = new javax.swing.JButton();
        Concession_Button = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        MovieShowtime_Button = new javax.swing.JButton();
        PurchaseTicket_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1120, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Customer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 220, 60));

        Logout_button.setText("Logout");
        Logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Logout_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        Concession_Button.setText("Concessions");
        Concession_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Concession_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Concession_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 290, 60));

        scrollPane.setMinimumSize(new java.awt.Dimension(400, 360));

        contentPanel.setPreferredSize(new java.awt.Dimension(400, 360));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(contentPanel);

        getContentPane().add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 790, 630));

        MovieShowtime_Button.setText("Movies & Showtimes");
        MovieShowtime_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieShowtime_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MovieShowtime_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 290, 60));

        PurchaseTicket_Button.setText("Purchase Ticket");
        PurchaseTicket_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseTicket_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PurchaseTicket_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 290, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Concession_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Concession_ButtonActionPerformed
        JOptionPane.showMessageDialog(this, "TODO");
    }//GEN-LAST:event_Concession_ButtonActionPerformed

    private void Logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_buttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "TODO");
    }//GEN-LAST:event_Logout_buttonActionPerformed

    private void MovieShowtime_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieShowtime_ButtonActionPerformed
        // TODO add your handling code here:
        loadMovies();
    }//GEN-LAST:event_MovieShowtime_ButtonActionPerformed

    private void PurchaseTicket_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseTicket_ButtonActionPerformed
        new PurchaseTicket_GUI(currentUser).setVisible(true);

    }//GEN-LAST:event_PurchaseTicket_ButtonActionPerformed
  
    private void loadMovies() {
        contentPanel.removeAll();
        List<Movie> movies = MovieIO.loadMovies("data/movies.txt");
        Map<String, List<String>> showtimesMap = ShowtimeIO.getShowtimesByMovie("data/showtimes.txt");

        for (Movie movie : movies) {
            JPanel moviePanel = new JPanel();
            moviePanel.setLayout(new BorderLayout());
            moviePanel.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            moviePanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 280));
            moviePanel.setPreferredSize(new Dimension(700, 280));

            JPanel left = new JPanel();
            left.setLayout(new BoxLayout(left, BoxLayout.Y_AXIS));
            left.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 0));
            left.setPreferredSize(new Dimension(200, 200));
            left.add(new JLabel("ID: " + movie.getMovieID()));
            left.add(new JLabel("Title: " + movie.getMovieTitle()));
            left.add(new JLabel("Genres: " + movie.getMovieGenres()));
            left.add(new JLabel("Run Time: " + movie.getMovieRuntime() + " minutes"));
            left.add(new JLabel(movie.getMovieRating()));
            left.add(new JLabel("Released: " + movie.getMovieReleaseDate()));

            JLabel poster = new JLabel();
            ImageIcon icon = new ImageIcon("data/posters/" + movie.getMovieTitle() + ".jpg");
            Image img = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            poster.setIcon(new ImageIcon(img));
            poster.setBorder(BorderFactory.createEmptyBorder(0, 20, 0, 0));
            poster.setPreferredSize(new Dimension(100, 200));

            JPanel right = new JPanel();
            right.setLayout(new BoxLayout(right, BoxLayout.Y_AXIS));
            right.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 0));
            right.setPreferredSize(new Dimension(250, 200));
            right.add(new JLabel("Showtimes:"));
            List<String> times = showtimesMap.get(movie.getMovieID());
            if (times != null) {
                for (String time : times) {
                    right.add(new JLabel(time));
                }
            } else {
                right.add(new JLabel("No showtimes available."));
            }

            moviePanel.add(left, BorderLayout.WEST);
            moviePanel.add(poster, BorderLayout.CENTER);
            moviePanel.add(right, BorderLayout.EAST);

            contentPanel.add(Box.createVerticalStrut(10));
            contentPanel.add(moviePanel);
        }

        contentPanel.revalidate();
        contentPanel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Concession_Button;
    private javax.swing.JButton Logout_button;
    private javax.swing.JButton MovieShowtime_Button;
    private javax.swing.JButton PurchaseTicket_Button;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}