package netbeans_gui;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import model.Staff;
import service.AuthenticationService;
import model.Person;
import model.MovieTheaterSystem;
import model.Customer;
import javax.swing.JOptionPane;

import model.*;

/**
 *
 * @author Kahden Vienna
 */
public class LoginWindow_GUI extends javax.swing.JFrame {

    private MovieTheaterSystem system;
    private AuthenticationService authService;
    /**
     * Creates new form LoginWindow_GUI7
     */
    public LoginWindow_GUI() {
        initComponents();
        system = new MovieTheaterSystem();
        authService = system.getAuthService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_Label = new javax.swing.JLabel();
        UserInput_TextField = new javax.swing.JTextField();
        PasswordInput_PasswordField = new javax.swing.JPasswordField();
        Login_Button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Window");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(640, 360));
        setPreferredSize(new java.awt.Dimension(640, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_Label.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Login_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login_Label.setText("Login");
        getContentPane().add(Login_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        UserInput_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserInput_TextField.setToolTipText("Username");
        UserInput_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInput_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserInput_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 180, 30));

        PasswordInput_PasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordInput_PasswordField.setToolTipText("Password");
        getContentPane().add(PasswordInput_PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 180, 30));

        Login_Button.setText("Login");
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 140, 30));

        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 140, 30));

        jButton2.setText("Skip");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 100, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserInput_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInput_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInput_TextFieldActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        // TODO add your handling code here:
        String username = UserInput_TextField.getText();
        String password = new String(PasswordInput_PasswordField.getPassword());
        
        Person person = authService.authenticate(username, password);
        
        if (person != null) {
            JOptionPane.showMessageDialog(this, "Login succesful! Welcome, " + person.getName());
            this.dispose();
            if (person instanceof Customer) {
                java.awt.EventQueue.invokeLater(() -> {
                new CustomerMenu_GUI().setVisible(true);
            });
            } else if (person instanceof Staff) {
                // TODO: Open staff GUI here
                JOptionPane.showMessageDialog(this, "Logged in as staff. (Add staff GUI here)");
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
     
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "TODO");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "TODO");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindow_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindow_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindow_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_Button;
    private javax.swing.JLabel Login_Label;
    private javax.swing.JPasswordField PasswordInput_PasswordField;
    private javax.swing.JTextField UserInput_TextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
